<a href="https://colab.research.google.com/github/astuteIsrael/DSN-AI-Bootcamp-Qualification-2024/blob/main/test_predictions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

In [ ]:
# import the data

train = pd.read_csv('/content/Train Dataset .csv')
test = pd.read_csv('/content/Test Dataset.csv')
vd = pd.read_csv('/content/Variable_Definitions.csv')
submit = pd.read_csv('/content/Sample Submission.csv')
# Display first few rows to inspect the data
print(train_data.head())
print(test_data.head())

      Id  Age  Sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0  16167   33    0   1       158   205    1        0      154      0      1.5
1  11275   53    1   2       198   154    0        1      104      0      0.8
2  13251   37    1   2       101   202    1        0      155      0      2.1
3  19921   75    0   0       113   306    1        2       88      1      4.9
4  11293   35    1   2       139   419    1        1      166      1      0.9

   slope  ca  thal  target
0      1   4     1       1
1      2   1     0       0
2      1   3     1       1
3      0   2     2       1
4      2   4     0       1
      Id  Age  Sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0  16501   70    1   0       163   495    0        2      170      1      2.0
1  10444   61    1   0       131   238    0        2       74      1      4.9
2  14288   53    1   0        95   558    1        1       73      1      0.7
3  10409   37    0   1       178   287    0        1      192      1      5.7
4  17330   35    0   3       104   281    0        0      122      0      1.3

   slope  ca  thal
0      1   0     1
1      2   2     2
2      1   1     0
3      1   0     0
4      1   4     3

In [ ]:
train.head(10)

,Id,Age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,16167,33,0,1,158,205,1,0,154,0,1.5,1,4,1,1
1,11275,53,1,2,198,154,0,1,104,0,0.8,2,1,0,0
2,13251,37,1,2,101,202,1,0,155,0,2.1,1,3,1,1
3,19921,75,0,0,113,306,1,2,88,1,4.9,0,2,2,1
4,11293,35,1,2,139,419,1,1,166,1,0.9,2,4,0,1
5,13835,69,1,3,164,280,0,0,88,0,5.0,0,0,0,0
6,16226,44,0,2,134,129,0,0,71,1,5.2,0,3,3,1
7,19944,32,1,0,164,341,1,1,93,1,5.4,0,3,0,1
8,12028,36,0,0,199,198,1,2,151,1,2.2,2,0,0,1
9,18599,60,1,1,126,389,0,1,79,0,2.6,2,0,2,1

In [ ]:
test.head()

,id,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,16501,70,1,0,163,495,0,2,170,1,2.0,1,0,1
1,10444,61,1,0,131,238,0,2,74,1,4.9,2,2,2
2,14288,53,1,0,95,558,1,1,73,1,0.7,1,1,0
3,10409,37,0,1,178,287,0,1,192,1,5.7,1,0,0
4,17330,35,0,3,104,281,0,0,122,0,1.3,1,4,3

In [ ]:

test.head(10)

,id,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,16501,70,1,0,163,495,0,2,170,1,2.0,1,0,1
1,10444,61,1,0,131,238,0,2,74,1,4.9,2,2,2
2,14288,53,1,0,95,558,1,1,73,1,0.7,1,1,0
3,10409,37,0,1,178,287,0,1,192,1,5.7,1,0,0
4,17330,35,0,3,104,281,0,0,122,0,1.3,1,4,3
5,13414,39,1,1,149,129,0,0,182,0,5.0,2,0,2
6,13447,30,0,0,161,466,0,0,202,0,3.1,0,3,1
7,16464,70,1,0,195,126,0,0,135,0,0.3,1,3,1
8,10846,67,1,0,102,448,1,0,191,0,5.0,0,3,1
9,13887,70,0,2,107,240,1,2,84,0,2.2,1,0,0

In [ ]:
vd.head(100)

                                             Variable defination
0                                                            age
1                                                            sex
2                                     chest pain type (4 values)
3                                         resting blood pressure
4                                     serum cholestoral in mg/dl
5                                fasting blood sugar > 120 mg/dl
6            resting electrocardiographic results (values 0,1,2)
7                                    maximum heart rate achieved
8                                        exercise induced angina
9   oldpeak = ST depression induced by exercise relative to rest
10                     the slope of the peak exercise ST segment
11           number of major vessels (0-3) colored by flourosopy
12     thal: 0 = normal; 1 = fixed defect; 2 = reversable defect

In [ ]:

train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7303 entries, 0 to 7302
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Id        7303 non-null   int64
 1   Age       7303 non-null   int64
 2   Sex       7303 non-null   int64
 3   cp        7303 non-null   int64
 4   trestbps  7303 non-null   int64
 5   chol      7303 non-null   int64
 6   fbs       7303 non-null   int64
 7   restecg   7303 non-null   int64
 8   thalach   7303 non-null   int64
 9   exang     7303 non-null   int64
 10  oldpeak   7303 non-null   float64
 11  slope     7303 non-null   int64
 12  ca        7303 non-null   int64
 13  thal      7303 non-null   int64
 14  target    7303 non-null   int64
dtypes: float64(1), int64(14)
memory usage: 855.9 KB

In [ ]:
train.describe()

,Id,Age,Sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000,7303.000000
mean,15021.535396,53.172669,0.499658,1.502533,147.447487,342.805970,0.493085,1.013008,136.506093,0.503218,3.129851,0.991510,2.019033,1.502259,0.813501
std,2886.026080,14.185970,0.500034,1.115594,31.099538,127.291998,0.499986,0.815806,38.141966,0.500024,1.791160,0.817291,1.410546,1.113137,0.389535
min,10001.000000,29.000000,0.000000,0.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,12521.500000,41.000000,0.000000,1.000000,120.000000,231.000000,0.000000,0.000000,104.000000,0.000000,1.600000,0.000000,1.000000,1.000000,1.000000
50%,15054.000000,53.000000,0.000000,1.000000,148.000000,341.000000,0.000000,1.000000,137.000000,1.000000,3.100000,1.000000,2.000000,1.000000,1.000000
75%,17513.500000,65.000000,1.000000,3.000000,174.000000,450.000000,1.000000,2.000000,170.000000,1.000000,4.700000,2.000000,3.000000,2.000000,1.000000
max,19998.000000,77.000000,1.000000,3.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [ ]:
train['target'].value_counts()

target
1    5941
0    1362
Name: count, dtype: int64

In [ ]:
test.shape

(2697, 14)

In [ ]:
submit.shape

(2697, 1)

In [ ]:
train.isna().sum()

Id          0
Age         0
Sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
train.duplicated().sum()

0

In [ ]:
# Check for missing values and handle them
print(train_data.isnull().sum())

# Fill missing values (example with median, can be customized)
train_data.fillna(train_data.median(), inplace=True)

# Split features (X) and target (y)
X = train_data.drop(columns=['target'])
y = train_data['target']

# Scale the features (Standardization)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

Id          0
Age         0
Sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [ ]:
# Split data into training and validation sets (80% train, 20% validation)
X_train, X_val, y_train, y_val = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
# Initialize XGBoost classifier
xgb_model = XGBClassifier(random_state=42)

# Set up Stratified K-Fold Cross-Validation
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Perform cross-validation on XGBoost model
xgb_cv_results = cross_val_score(xgb_model, X_scaled, y, cv=kfold, scoring='accuracy', verbose=2)
print(f"XGBoost Cross-Validation Accuracy: {xgb_cv_results.mean()} (+/- {xgb_cv_results.std()})")

[CV] END .................................................... total time=   0.2s
[CV] END .................................................... total time=   0.2s
[CV] END .................................................... total time=   0.2s
[CV] END .................................................... total time=   0.2s
[CV] END .................................................... total time=   0.2s
XGBoost Cross-Validation Accuracy: 0.811721845611469 (+/- 0.007004245831598185)

In [ ]:
# Initialize Random Forest classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Create an ensemble model using VotingClassifier
ensemble_model = VotingClassifier(estimators=[('xgb', xgb_model), ('rf', rf_model)], voting='soft')

# Perform cross-validation on Ensemble model
ensemble_cv_results = cross_val_score(ensemble_model, X_scaled, y, cv=kfold, scoring='accuracy', verbose=2)
print(f"Ensemble Model Cross-Validation Accuracy: {ensemble_cv_results.mean()} (+/- {ensemble_cv_results.std()})")

[CV] END .................................................... total time=   0.9s
[CV] END .................................................... total time=   0.9s
[CV] END .................................................... total time=   0.9s
[CV] END .................................................... total time=   0.9s
[CV] END .................................................... total time=   0.9s
Ensemble Model Cross-Validation Accuracy: 0.8104895314712197 (+/- 0.006030021430305819)

In [ ]:
# Train the ensemble model on the full training set
ensemble_model.fit(X_train, y_train)

# Predict on the validation set
y_val_pred = ensemble_model.predict(X_val)

# Evaluate the ensemble model on validation data
accuracy = accuracy_score(y_val, y_val_pred)
roc_auc = roc_auc_score(y_val, y_val_pred)

print(f"Validation Accuracy (Ensemble Model): {accuracy}")
print(f"Validation AUC-ROC (Ensemble Model): {roc_auc}")
print("Classification Report (Ensemble Model):")
print(classification_report(y_val, y_val_pred))

Validation Accuracy (Ensemble Model): 0.8288843258042436
Validation AUC-ROC (Ensemble Model): 0.7045619035419202
Classification Report (Ensemble Model):
              precision    recall  f1-score   support

           0       0.52      0.51      0.52       260
           1       0.89      0.90      0.90      1201

    accuracy                           0.83      1461
   macro avg       0.71      0.70      0.71      1461
weighted avg       0.83      0.83      0.83      1461

In [ ]:
# Scale the test data using the same scaler
test_data_scaled = scaler.transform(test_data)

# Predict on the test dataset using the ensemble model
test_predictions = ensemble_model.predict(test_data_scaled)

# Prepare the submission file
sample_submission['target'] = test_predictions
sample_submission.to_csv('Ensemble_Heart_Disease_Predictions.csv', index=False)

print("Submission file 'Ensemble_Heart_Disease_Predictions.csv' generated successfully.")

Submission file 'Ensemble_Heart_Disease_Predictions.csv' generated successfully.